const especes = [
	{ id: "1", name: "Allium cepa", genre_id: "9", famille_id: "7" },
	{
		id: "2",
		name: "Phaseolus vulgaris",
		genre_id: "10",
		famille_id: "3",
	},
	{
		id: "3",
		name: "Brassica oleracea",
		genre_id: "3",
		famille_id: "6",
	},
	{
		id: "4",
		name: "Brassica rapa",
		genre_id: "3",
		famille_id: "6",
	},
	{
		id: "5",
		name: "Cucurbita maxima",
		genre_id: "5",
		famille_id: "2",
	},
	{
		id: "6",
		name: "Cucurbita moschata",
		genre_id: "5",
		famille_id: "2",
	},
	{
		id: "7",
		name: "Cucumis sativus",
		genre_id: "6",
		famille_id: "2",
	},
	{ id: "8", name: "Cucumis melo", genre_id: "6", famille_id: "2" },
	{
		id: "9",
		name: "Solanum lycopersicum",
		genre_id: "1",
		famille_id: "1",
	},
	{
		id: "10",
		name: "Solanum tuberosum",
		genre_id: "1",
		famille_id: "1",
	},
	{
		id: "11",
		name: "Lactuca sativa",
		genre_id: "7",
		famille_id: "4",
	},
	{
		id: "12",
		name: "Calendula officinalis",
		genre_id: "8",
		famille_id: "4",
	},
	{
		id: "13",
		name: "Prunus persica",
		genre_id: "12",
		famille_id: "5",
	},
	{
		id: "14",
		name: "Malus sylvestris",
		genre_id: "14",
		famille_id: "5",
	},
	{
		id: "15",
		name: "Rubus idaeus",
		genre_id: "13",
		famille_id: "5",
	},
	{
		id: "16",
		name: "Rubus fruticosus",
		genre_id: "13",
		famille_id: "5",
	},
	{
		id: "17",
		name: "Pisum sativum",
		genre_id: "11",
		famille_id: "3",
	},
	{
		id: "18",
		name: "Raphanus sativus",
		genre_id: "4",
		famille_id: "6",
	},
	{
		id: "19",
		name: "Capsicum annuum",
		genre_id: "2",
		famille_id: "1",
	},
	{
		id: "20",
		name: "Capsicum chinense",
		genre_id: "2",
		famille_id: "1",
	},
	{
		id: "21",
		name: "Capsicum frutescens",
		genre_id: "2",
		famille_id: "1",
	},
	{
		id: "22",
		name: "Capsicum baccatum",
		genre_id: "2",
		famille_id: "1",
	},
	{
		id: "23",
		name: "Capsicum pubescens",
		genre_id: "2",
		famille_id: "1",
	},
	{
		id: "24",
		name: "Allium porrum",
		genre_id: "9",
		famille_id: "7",
	},
	{
		id: "25",
		name: "Allium sativum",
		genre_id: "9",
		famille_id: "7",
	},
	{
		id: "26",
		name: "Allium schoenoprasum",
		genre_id: "9",
		famille_id: "7",
	},
	{
		id: "27",
		name: "Solanum melongena",
		genre_id: "1",
		famille_id: "1",
	},
	{
		id: "28",
		name: "Artemisia dracunculus",
		genre_id: "15",
		famille_id: "4",
	},
];

module.exports = especes;
